# The URL the site will be built for
base_url = "https://newtbytes.cc"

title = "Newt's Cove"
description = "Ness Shannon's personal website, blog, microblog, and more!"
author = "newtbytes"

generate_feeds = true
generate_sitemap = true
feed_filenames = ["atom.xml", "rss.xml"]

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# since I often write on platforms that automatically insert smart punctuation,
# might as well make sure it's consistent across the whole site
smart_punctuation = true
external_links_no_follow = true

[markdown.highlighting]
error_on_missing_language = true
theme = "catppuccin-frappe"

# TODO: figure out taxonomies

[extra]
family_mode = true
