# The URL the site will be built for
base_url = "https://newtbytes.cc"

author = "newtbytes"

generate_feeds = true

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# since I often write on platforms that automatically insert smart punctuation,
# might as well make sure it's consistent across the whole site
smart_punctuation = true

[markdown.highlighting]
theme = "catppuccin-frappe"

# TODO: figure out taxonomies

[extra]
family_mode = true
