map $http_user_agent $user_agent_sus {
    $SUS_USER_AGENT_REGEX 1;
    default 0;
}

map $http_cf_postal_code $postal_code_sus {
    $SUS_POSTAL_CODE_REGEX 1;
    default 0;
}

map $http_cf_city $city_sus {
    $SUS_CITY_REGEX 1;
    default 0;
}

map $city_sus$postal_code_sus$user_agent_sus $should_reroute {
    111 1;
    011 1;
    010 1;

    default 0;
}

upstream cloudflare_pages {
    server website-family-mode.pages.dev;
}

upstream github_pages {
    server 185.199.108.153;
    server 185.199.109.153;
    server 185.199.110.153;
    server 185.199.111.153;
}

map $should_reroute $upstream {
    1 cloudflare_pages;
    0 github_pages;
    default github_pages;
}

server {
    listen 80;
    server_name newtbytes.cc "";

    location / {
        proxy_pass https://$upstream;
    }
}