include "router.detect.conf";

upstream cloudflare_pages {
    server website-family-mode.pages.dev;
}

upstream github_pages {
    server 185.199.108.153;
    server 185.199.109.153;
    server 185.199.110.153;
    server 185.199.111.153;
}

map $should_reroute $upstream {
    1 cloudflare_pages;
    0 github_pages;
    default github_pages;
}

server {
    listen 80;
    server_name newtbytes.cc "";

    location / {
        proxy_pass https://$upstream;
    }
}