name: Build, test, and deploy Zola website
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  ZOLA_VERSION: 0.22.1
  BUILD_FLAGS: --drafts

jobs:
  # test:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: checkout
  #       uses: actions/checkout@v6.0.2

  #     - name: Install zola
  #       uses: taiki-e/install-action@v2
  #       with:
  #         tool: zola@${{ env.ZOLA_VERSION }}

  # FIXME: - run: zola check ${{ env.BUILD_FLAGS }}

  build:
    runs-on: ubuntu-latest

    # needs: [test]

    steps:
      - name: checkout
        uses: actions/checkout@v6.0.2

      - name: Build Zola + upload Pages artifact
        uses: getzola/github-pages@435a833fd3f1edcb28d70576c89e30a6365cd8f7
        with:
          zola_version: v${{ env.ZOLA_VERSION }}
          build_flags: ${{ env.BUILD_FLAGS }}

  deploy-neocities:
    runs-on: ubuntu-latest

    # needs: [test]

    steps:
      - name: checkout
        uses: actions/checkout@v6.0.2

      - name: Install zola
        uses: taiki-e/install-action@v2
        with:
          tool: zola@${{ env.ZOLA_VERSION }}

      - name: Build site for neocities
        env:
          DEPLOY_TGT: neocities
        run: zola build ${{ env.BUILD_FLAGS }}

      - name: Deploy to neocities
        uses: bcomnes/deploy-to-neocities@v3.0.5
        with:
          cleanup: true
          neocities_supporter: false
          preview_before_deploy: true
          dist_dir: public
          api_token: ${{ secrets.NEOCITIES_API_KEY }}
          api_key: ${{ secrets.NEOCITIES_API_KEY }}

  deploy:
    runs-on: ubuntu-latest

    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
